// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProzorroDataMining.Data;
using ProzorroDataMining.Data.Database;

#nullable disable

namespace ProzorroDataMining.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProzorroDataMining.Domain.Models.Contract", b =>
                {
                    b.Property<Guid>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("TenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ContractId");

                    b.HasIndex("TenderId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Models.Supplier", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SupplierId");

                    b.HasIndex("TenderId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Models.Tender", b =>
                {
                    b.Property<string>("TenderId")
                        .HasColumnType("text");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcuringEntity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TenderDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenderId");

                    b.ToTable("Tenders");
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Models.Contract", b =>
                {
                    b.HasOne("ProzorroDataMining.Domain.Models.Tender", null)
                        .WithMany("Contracts")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Models.Supplier", b =>
                {
                    b.HasOne("ProzorroDataMining.Domain.Models.Tender", null)
                        .WithMany("Suppliers")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Models.Tender", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
